---

## copy installer
- name: copy winlogbeat installer
  ansible.builtin.copy:
    src: /home/2_ansible_resource_provisioning/remote_host_files/elk/winlogbeat-8.9.0-windows-x86_64.zip
    dest: C:\Users\TestAdmin\Downloads\winlogbeat.zip

- name: extract archive
  win_shell: |
    powershell -command "Expand-Archive -Force C:\Users\TestAdmin\Downloads\winlogbeat.zip C:\Program Files\Winlogbeat"
    powershell -command "Move-Item -Path C:\Program Files\Winlogbeat\winlogbeat-8.9.0-windows-x86_64\* -Destination C:\Program Files\Winlogbeat"
    powershell -command "Set-ExecurtionPolicy Unrestricted"


- name: copy config
  template:
    src: winlogbeat.yml
    dest: C:\Program Files\Winlogbeat\winlogbeat.yml


- name: install
  win_shell: |    
    .\install-service-winlogbeat.ps1
    net start winlogbeat
    



