---

## copy installer
- name: copy winlogbeat installer
  ansible.windows.win_copy:
    src: /home/2_ansible_resource_provisioning/remote_host_files/elk/winlogbeat-7.17.0-windows-x86_64.zip
    dest: C:\Users\TestAdmin\Downloads\winlogbeat.zip

- name: extract archive
  win_shell: |
    powershell -command "Expand-Archive -Force C:\Users\TestAdmin\Downloads\winlogbeat.zip C:\Program Files\Winlogbeat"
    powershell -command "Move-Item -Path C:\Program Files\Winlogbeat\winlogbeat-7.17.0-windows-x86_64\* -Destination C:\Program Files\Winlogbeat"
    powershell -command "Set-ExecutionPolicy Unrestricted"


- name: copy config
  ansible.windows.win_template:
    src: winlogbeat.yml
    dest: C:\Program Files\Winlogbeat\winlogbeat.yml


- name: install
  win_shell: |    
    .\install-service-winlogbeat.ps1
    net start winlogbeat
    

## todo: copy selected channels file to windows right next to log exporter

