--- 


- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: /home/iai/attack_range_openstack/2_ansible_resource_provisioning/remote_host_files/apt29/Scenario_2
    dest: /home/"{{ ansible_user }}"/poshc2/apt29/payloads
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"