- hosts: all
  gather_facts: True
  become: true
  vars:  
    hostname: elk_server
  roles:
    - linux_common
    - set_hostname_linux
    - java_linux
    - elasticsearch_linux
    - kibana_linux
    - filebeat_linux
    - metricbeat_linux
    - cloudtrail_logs
    - carbon_black_cloud_logs
    - crowdstrike_falcon_logging
    - guacamole_terraform

