- hosts: distro_kali
  gather_facts: False
  become: true
  roles:
    - set_hostname_linux
    - linux_common
#   - update_sysmon_config_linux
#    - linux_universal_forwarder
#    - linux_sysmon
#    - linux_install_art
#    - linux_osquery        
    - install_posh_c2
    - copy_kali_files
