- hosts: kali
  gather_facts: False
  become: true
  vars:  
    hostname: kali
  roles:
    - set_hostname_linux
    - linux_common
    - copy_kali_files
   # - red_team_tools_terraform
    #- atomic_red_team
    - install_posh_c2
