- hosts: all
  gather_facts: True
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_port: 5985
  roles:
    - create_domain_controller
    #- windows_domain_controller