---


- name: restart auditd
  become: true
  ansible.builtin.raw: |    
    sudo service auditd start
    sudo systemctl enable auditd
    sudo auditctl -R /etc/audit/rules.d/audit.rules
    sudo service auditd force-reload
  args:
    executable: /bin/bash   