---


- name: restart auditd
  become: true
  ansible.builtin.raw: |    
    sudo service auditd start
    sudo systemctl enable auditd
    sudo auditctl -R /home/{{ ansible_user }}/audit.rules
    sudo service auditd reload
  args:
    executable: /bin/bash   