--- 


- name: clean logs folder
  ansible.windows.win_powershell:
    script: |
      If((Test-Path -Path "C:\Export-EventLogs\EventLogs\*"))
      {
        Remove-Item -Recurse -Force -LiteralPath "C:\Export-EventLogs\EventLogs\"
        New-Item -ItemType Directory -Force -Path C:\Export-EventLogs\EventLogs\
      }     

- name: log exporter script
  ansible.windows.win_powershell:
    script: |
      cd C:\Export-EventLogs
      Get-Content -Path "C:\Export-EventLogs\selected_channels.txt" | ForEach-Object {
        .\Export-EventLogs.ps1 -EventLogNames $_
      }       

- name: collect Tab-formatted logs
  ansible.windows.win_powershell:
    script: |
      Get-Content -Path "C:\Export-EventLogs\selected_channels.txt" | ForEach-Object {
        $filename = -join("C:\Export-EventLogs\EventLogs\", $_, "_tab.txt")
        $filename = $filename.Replace('/','-')
        IF($_ -ne 'Microsoft-Windows-Sysmon/Operational') {
          Get-WinEvent -LogName $_ | Select-Object -Property KeywordDisplayName, TimeCreated, Source, ProviderName, Id, TaskDisplayName, LevelDisplayName, Message | Export-Csv -Path $filename -Delimiter "`t" -NoTypeInformation
        }
      }

- name: collect complete log text exports
  ansible.windows.win_powershell:
    script: |
      Get-Content -Path "C:\Export-EventLogs\selected_channels.txt" | ForEach-Object {
        $filename = -join("C:\Export-EventLogs\EventLogs\", $_, "_comma.txt")
        $filename = $filename.Replace('/','-')
        IF($_ -ne 'Microsoft-Windows-Sysmon/Operational') {
          Get-WinEvent -LogName $_ | Export-Csv -Path $filename -NoTypeInformation
        }
      }      

- name: copy single logs
  ansible.windows.win_powershell:
    script: |
      Copy-Item "C:\Windows\Logs\file_read.etl" -Destination "C:\Export-EventLogs\EventLogs"
      Copy-Item "C:\Windows\Logs\Registry_read.etl" -Destination "C:\Export-EventLogs\EventLogs"
      Copy-Item "C:\Windows\Logs\Powershell_payload.etl" -Destination "C:\Export-EventLogs\EventLogs"
      Copy-Item "C:\Windows\Logs\alpc.etl" -Destination "C:\Export-EventLogs\EventLogs"
      Copy-Item "C:\Windows\System32\winevt\Logs\powershell_audit.evtx" -Destination "C:\Export-EventLogs\EventLogs"
      Copy-Item "C:\Windows\System32\winevt\Logs\sysmon_audit.evtx" -Destination "C:\Export-EventLogs\EventLogs"


- name: zip logs
  ansible.windows.win_powershell:
    script: |   
      $7zipPath = "$env:ProgramFiles\7-Zip\7z.exe"
      Set-Alias Start-SevenZip $7zipPath
      $Source = "C:\Export-EventLogs\EventLogs\"
      $Target = "C:\Export-EventLogs\{{ hostname }}_logs.zip"
      Start-SevenZip a -mx=9 $Target $Source


#   Compress-Archive -Path "C:\Export-EventLogs\EventLogs\" -DestinationPath "C:\Export-EventLogs\{{ hostname }}_logs.zip"

# todo: if this fails due to memory limitations, change to 7zip or somehow test, if compress archive fails and then use 7zip
- name: zip pcaps
  ansible.windows.win_powershell:
    script: |      
      $filesize = (Get-ChildItem -path C:\Export-EventLogs\capture.pcapng -Recurse | Measure-Object -Property Length -Sum).Sum / 1GB
      if ($filesize -lt '2') {
        Compress-Archive -Path "C:\Export-EventLogs\capture.pcapng" -DestinationPath "C:\Export-EventLogs\{{ hostname }}_pcap.zip"
      } 
      elseif ($filesize -ge '2') {
        $7zipPath = "$env:ProgramFiles\7-Zip\7z.exe"
        Set-Alias Start-SevenZip $7zipPath
        $Source = "C:\Export-EventLogs\capture.pcapng"
        $Target = "C:\Export-EventLogs\{{ hostname }}_pcap.zip"
        Start-SevenZip a -mx=9 $Target $Source      
      }
 

- name: Transfer logs to aggregation server
  ansible.windows.win_powershell:
    script: |
      $hostname = get-content env:computername
      if ($hostname.StartsWith("IT")) {
        scp -o StrictHostKeyChecking=no -i "C:\Users\{{ ansible_user }}\.ssh\id_ed25519_win" "C:\Export-EventLogs\{{ hostname }}_logs.zip" debian@10.0.1.12:"/home/debian/dataset/{{ hostname }}/logs/{{ hostname }}_logs.zip"
      }
      elseif ($hostname.StartsWith("OT")) {
        scp -o StrictHostKeyChecking=no -i "C:\Users\{{ ansible_user }}\.ssh\id_ed25519_win" "C:\Export-EventLogs\{{ hostname }}_logs.zip" debian@10.0.2.12:"/home/debian/dataset/{{ hostname }}/logs/{{ hostname }}_logs.zip"
      }


- name: Transfer pcaps to aggregation server
  ansible.windows.win_powershell:
    script: |
      $hostname = get-content env:computername
      if ($hostname.StartsWith("IT")) {
        scp -o StrictHostKeyChecking=no -i "C:\Users\{{ ansible_user }}\.ssh\id_ed25519_win" "C:\Export-EventLogs\{{ hostname }}_pcap.zip" debian@10.0.1.12:"/home/debian/dataset/{{ hostname }}/network/{{ hostname }}_pcap.zip"
      }
      elseif ($hostname.StartsWith("OT")) {
        scp -o StrictHostKeyChecking=no -i "C:\Users\{{ ansible_user }}\.ssh\id_ed25519_win" "C:\Export-EventLogs\{{ hostname }}_pcap.zip" debian@10.0.2.12:"/home/debian/dataset/{{ hostname }}/network/{{ hostname }}_pcap.zip"
      }

#scp -i C:\Users\TestAdmin\.ssh\id_ed25519_win C:\Export-EventLogs\IT-Win-PC-1_logs.zip debian@10.0.1.12:/home/debian/dataset/IT-Win-PC-1/IT-Win-PC-1_logs.zip
