---

- name: uninstall updates against PrintNightmare (CVE-2021-34527)
  ansible.windows.win_powershell:
    script: |
      wusa /uninstall /kb:5004945
      wusa /uninstall /kb:5004237
      wusa /uninstall /kb:5005394


- name: Re-enable the Print Spooler Service
  ansible.windows.win_powershell:
    script: |      
      sc config Spooler start= auto
      sc start Spooler


- name: set registry key to 0
  ansible.windows.win_regedit:
    path: HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Printers\PointAndPrint
    name: NoWarningNoElevationOnInstall
    data: 0


- name: set registry key to 0
  ansible.windows.win_regedit:
    path: HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Printers\PointAndPrint
    name: UpdatePromptSettings
    data: 0


- name: set registry key to 0
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Print
    name: RpcAuthnLevelPrivacyEnabled
    data: 0


- name: disable printer driver isolation 
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Printers
    name: PrintDriverIsolationExecutionPolicy
    data: 0
    type: dword


- name: allow unsigned print drivers
  win_shell: |
    bcdedit /set testsigning on
    bcdedit /set nointegritychecks off 