proxy:
  # set dynamically
  vars:
    samba_users:
      - username: debian
        password: secret
ansible_contoller:
  # set dynamically

windows:
  hosts:
    IT-Win-DC:
      ansible_host: '10.0.1.14'
      ansible_user: 'TestAdmin'
      ansible_password: 'secreT123%'
      hostname: 'IT-Win-DC'
      create_domain: '1'
      join_domain: '1'
      install_red_team_tools: '1'
    OT-Win-DC:
      ansible_host: '10.0.2.14'
      ansible_user: 'TestAdmin'
      ansible_password: 'secreT123%'
      hostname: 'OT-Win-DC'
      create_domain: '1'
      join_domain: '1'
      install_red_team_tools: '1'   
    IT-Win-Share:
      ansible_host: '10.0.1.20'
      ansible_user: 'TestAdmin'
      ansible_password: 'secreT123%'
      hostname: 'IT-Win-Share'
      create_domain: '0'
      join_domain: '1'
      install_red_team_tools: '1'
    IT-Win-PC-1:
      ansible_host: '10.0.1.15'
      ansible_user: 'TestAdmin'
      ansible_password: 'secreT123%'
      hostname: 'IT-Win-PC-1'
      create_domain: '0'
      join_domain: '1'
      install_red_team_tools: '1'
    IT-Win-Server-1:
      ansible_host: '10.0.1.18'
      ansible_user: 'TestAdmin'
      ansible_password: 'secreT123%'   
      hostname: 'IT-Win-Server-1'
      create_domain: '0'
      join_domain: '1'
      install_red_team_tools: '1'      
    OT-Win-PC-1:
      ansible_host: '10.0.2.15'
      ansible_user: 'TestAdmin'
      ansible_password: 'secreT123%'
      hostname: 'OT-Win-PC-1'
      create_domain: '0'
      join_domain: '1'
      install_red_team_tools: '1'
    OT-Win-PC-2:
      ansible_host: '10.0.2.18'
      ansible_user: 'TestAdmin'
      ansible_password: 'secreT123%'
      hostname: 'OT-Win-PC-2'
      create_domain: '0'
      join_domain: '1'
      install_red_team_tools: '1'      
  vars:
    cloud_provider: openstack
    splunk_uf_win_url: 'https://download.splunk.com/products/universalforwarder/releases/9.0.5/windows/splunkforwarder-9.0.5-e9494146ae5c-x64-release.msi'
#    atomic_red_team_repo: redcanaryco
#    atomic_red_team_branch: master
#    prelude_operator_url: "https://download.prelude.org/latest?arch=x64&platform=linux&variant=zip&edition=headless"
    use_prebuilt_images_with_packer: 0
    win_sysmon_config: 'SwiftOnSecurity.xml'
    #ansible_connection: psrp
    #ansible_psrp_cert_validation: ignore
    ##ansible_psrp_operation_timeout: 120
    ##ansible_psrp_read_timeout: 150
    #ansible_psrp_protocol: https
    #ansible_port: 5986
    #ansible_psrp_proxy: 'socks5://localhost:1080'
    ansible_user: 'TestAdmin'
    ansible_password: 'secreT123%'
#    ansible_connection: ssh
    ansible_connection: winrm
    ansible_port: 5985
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_scheme: http
    ansible_winrm_http_proxy: "socks5://debian@10.1.3.191:1080"  #"socks5://socks_user:socks_password@socks_server:socks_port" 
    ansible_winrm_proxy: "socks5://debian@10.1.3.191:1080"
    ansible_winrm_operation_timeout_sec: 120
    ansible_winrm_read_timeout_sec: 150
    ansible_winrm_cert_key_pem: '~/.ssh/id_ed25519'
    ansible_winrm_message_encryption: never
    ansible_winrm_transport: basic    
    ansible_winrm_user: 'TestAdmin'
    ansible_winrm_password: 'secreT123%'
    attack_range_password: 'secreT123%'
#    byo_splunk_ip: '10.0.1.123'
#    ansible_ssh_common_args: '-vvvv -o ProxyCommand="ssh -vvvv -A -p 22 -W %h:%p -q debian@10.1.3.191" -o StrictHostKeyChecking=no'
#    ansible_ssh_common_args: '-vvvv -o StrictHostKeyChecking=no -o ControlMaster=auto -o ControlPersist=600s -o ControlPath="~/.ssh/mux2win-%r@%h:%p"'


debian:
  hosts:
    aggregation_server:
      ansible_host: '10.0.1.12'
      hostname: 'aggregation-server'     
    OT-PLC-Linux:
      ansible_host: '10.0.2.17'
      hostname: 'OT-PLC'      
    OT-HMI-Linux:       
      ansible_host: '10.0.2.16'
      hostname: 'OT-HMI'      
    APT-Download-Server:       
      ansible_host: '10.0.6.42'
      hostname: 'APT-Download-Server'            
  vars:
    ansible_user: 'debian'



ubuntu:
  hosts:
    IT-Linux-PC-1:
      ansible_host: '10.0.1.16'
      hostname: 'IT-Linux-PC-1'
  vars:
    ansible_user: 'ubuntu'



kali:
  hosts:
    IT-Inside-Attacker:
      ansible_host: '10.0.1.17'
      hostname: 'IT-Inside-Attacker'
    APT-Outside-Attacker:
      ansible_host: '10.0.4.97' 
      hostname: 'APT-Outside-Attacker'     
    APT-C2-Server:
      ansible_host: '10.0.5.64'
      hostname: 'APT-C2-Server'
  vars:
    ansible_user: 'debian'




access_via_proxy:
  hosts:
    aggregation_server:
    IT-Inside-Attacker:
    APT-Outside-Attacker:
    APT-C2-Server:
    APT-Download-Server:
    IT-Linux-PC-1:   
    IT-Win-DC:
    OT-Win-DC:
    IT-Win-Share:
    IT-Win-PC-1:
    IT-Win-Server-1:
    OT-Win-PC-1:
    OT-Win-PC-2:



access_via_proxy_2:
    OT-PLC-Linux:
    OT-HMI-Linux: 


access_from_proxy:





audit_linux: 
  hosts:
    OT-PLC-Linux:
    OT-HMI-Linux: 
    IT-Inside-Attacker:
    IT-Linux-PC-1:



# plcs_linux:
#   hosts:
#     hmi_linux:
#       hostname: 'hmi-linux'
#       absible_host: '10.0.2.16' # '10.0.1.20'
#       ansible_user: 'ubuntu'
#       ansible_ssh_common_args': f'-A -vvvv -o ProxyCommand="ssh -vvvv -A -p 22 -W %h:%p -q -l debian 10.1.3.152" -o StrictHostKeyChecking=no
#     plc_linux:
#       hostname: 'plc-linux'
#       ansible_host: '10.0.2.17'  # '10.0.1.19'
#       ansible_user: 'ubuntu'
#       ansible_ssh_common_args': f'-A -vvvv -o ProxyCommand="ssh -vvvv -A -p 22 -W %h:%p -q -l debian 10.1.3.152" -o StrictHostKeyChecking=no

