
- name: check if BOTSv3 app exists
  stat:
    path: /opt/splunk/etc/apps/botsv3_data_set
  register: botsv3_app

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /opt/splunk/etc/apps
    state: directory
    mode: '0755'

- name: download BOTSv3 dataset
  unarchive:
    src: 'https://botsdataset.s3.amazonaws.com/botsv3/botsv3_data_set.tgz'
    dest: /opt/splunk/etc/apps 
    owner: "{{ owner }}"
    group: "{{ group }}"
    remote_src: yes
  when: botsv3_app.stat.exists == False
