---
#
# Installing Filebeat
#

# Install Filebeat 


- name: Add Elasticsearch apt key
  apt_key:
   url: "https://packages.elastic.co/GPG-KEY-elasticsearch"
   state: present


- name: Adding Elasticsearch repo
  apt_repository:
   repo: deb https://artifacts.elastic.co/packages/5.x/apt stable main
   state: present


- name: Install Filebeat with apt
  apt:
   name: apt-transport-https
   update_cache: yes


- name: Install Filebeat with apt
  apt:
   name: filebeat
   update_cache: yes

# - name: Updating the port in config file 
#   lineinfile:
#    destfile: /etc/filebeat/filebeat.yml
#    regexp: 'hosts: ["localhost:9200"]'
#    line: 'hosts: ["elk-server:9200", "10.0.2.13:9200", "10.0.1.13:9200", "127.0.0.1:9200"]'


# - name: Updating the port in config file 
#   lineinfile:
#    destfile: /etc/filebeat/filebeat.yml
#    regexp: 'host: "localhost:5601"'
#    line: 'host: "10.0.2.13:5601"'


- name: copy filebeat installer
  ansible.builtin.copy:
    src: /home/iai/attack_range_openstack/2_ansible_resource_provisioning/remote_host_files/elk/filebeat-5.6.16-amd64.deb
    dest: /home/ubuntu/filebeat.deb


# - name: Install splunk uf
#   become: yes
#   apt: deb="/home/ubuntu/filebeat.deb"


# - name: install via dpkg
#   ignore_errors: true
#   ansible.builtin.shell: >
#     sudo dpkg -i /home/ubuntu/filebeat.deb -y



- name: Replace default filebeat.yml configurations
  template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml


- name: activate modules
  ignore_errors: true
  ansible.builtin.shell: >
    export LC_ALL="C.UTF-8";
    sudo bash /usr/bin/filebeat.sh -configtest -e
    sudo systemctl enable filebeat
    sudo systemctl start filebeat

#    sudo filebeat modules enable netflow osquery auditd iptables oracle system 
#    filebeat setup -e


# Starting Filebeat

- name: Starting Filebeat
  service:
   name: filebeat
   state: started
