#cloud-config
users:
  - name: Admin
    inactive: True
  - name: TestAdmin
    passwd: secreT123%
    primary_group: Administrators
    inactive: False
  - name: TestUser
    passwd: secreT123%
    primary_group: Users
    inactive: False  
runcmd:
  - |
    netsh advfirewall firewall add rule name="WinRM 5985" protocol=TCP dir=in localport=5985 action=allow
    netsh advfirewall firewall add rule name="WinRM 5986" protocol=TCP dir=in localport=5986 action=allow
    netsh advfirewall firewall add rule name="Splunk" protocol=TCP dir=in localport=8000 action=allow
    netsh advfirewall firewall add rule name="Splunk" protocol=TCP dir=out localport=8000 action=allow  
    netsh advfirewall firewall add rule name="Splunk" protocol=TCP dir=in localport=8089 action=allow
    netsh advfirewall firewall add rule name="Splunk" protocol=TCP dir=out localport=8089 action=allow  
    netsh advfirewall firewall add rule name="Splunk" protocol=TCP dir=in localport=8065 action=allow
    netsh advfirewall firewall add rule name="Splunk" protocol=TCP dir=out localport=8065 action=allow
    netsh advfirewall firewall add rule name="Splunk" protocol=TCP dir=in localport=8191 action=allow
    netsh advfirewall firewall add rule name="Splunk" protocol=TCP dir=out localport=8191 action=allow  
    powershell -Command "Set-ItemProperty -Path HKLM:SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU -Name UseWUServer -Value 0"
    powershell -Command "Restart-Service -Name wuauserv -Force"
    powershell -Command "Get-WindowsCapability -Online | Where-Object Name -like 'OpenSSH.Server*' | Add-WindowsCapability -Online"
    powershell -Command " Echo Y | powershell Set-Item WSMan:\localhost\Client\TrustedHosts -Value '10.0.1.12,10.0.1.14,10.0.1.15,10.0.1.16,10.0.1.17,10.0.1.18,10.0.1.5,10.1.3.152'"
    powershell -Command " Echo Y | powershell Set-Item WSMan:\localhost\Client\TrustedHosts -Value '*'"
    echo test >> C:\hosts.txt
    powershell Set-Service -Name ssh-agent -StartupType Automatic
    powershell Set-Service -Name sshd -StartupType Automatic
    powershell New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\WDigest" -Name UseLogonCredential -Value 1 -Force
    netsh advfirewall firewall add rule name "SSH" dir=in action=allow enable=yes program="C:\Windows\System32\OpenSSH\ssh"
    netsh advfirewall firewall add rule name "SSH-add" dir=in action=allow enable=yes program="C:\Windows\System32\OpenSSH\ssh-add"
    netsh advfirewall firewall add rule name "SSH-agent" dir=in action=allow enable=yes program="C:\Windows\System32\OpenSSH\ssh-agent"
    netsh advfirewall firewall add rule name "SSH-keygen" dir=in action=allow enable=yes program="C:\Windows\System32\OpenSSH\ssh-keygen"
    netsh advfirewall firewall add rule name "SSH-keyscan" dir=in action=allow enable=yes program="C:\Windows\System32\OpenSSH\ssh-keyscan"
    netsh advfirewall firewall add rule name "SSH" dir=out action=allow enable=yes program="C:\Windows\System32\OpenSSH\ssh"
    netsh advfirewall firewall add rule name "SSH-add" dir=out action=allow enable=yes program="C:\Windows\System32\OpenSSH\ssh-add"
    netsh advfirewall firewall add rule name "SSH-agent" dir=out action=allow enable=yes program="C:\Windows\System32\OpenSSH\ssh-agent"
    netsh advfirewall firewall add rule name "SSH-keygen" dir=out action=allow enable=yes program="C:\Windows\System32\OpenSSH\ssh-keygen"
    netsh advfirewall firewall add rule name "SSH-keyscan" dir=out action=allow enable=yes program="C:\Windows\System32\OpenSSH\ssh-keyscan"  
    net start "ssh-agent"
    net start "ssh"
    net start "sshd"
    powershell Set-TimeZone -Id 'W. Europe Standard Time'
    powershell Set-WinSystemLocale de-DE
    powershell Set-WinUserLanguageList -Force 'de-DE'
    powershell Set-WinUILanguageOverride -Language en-US
    echo 'start winrm setup' > C:\winrm_log.txt
    echo 'quickconfig:' >> C:\winrm_log.txt
    echo '' >> C:\winrm_log.txt
    powershell winrm quickconfig >> C:\winrm_log.txt
    echo 'winrs shell memory:' >> C:\winrm_log.txt
    echo '' >> C:\winrm_log.txt
    winrm set winrm/config/winrs @{MaxMemoryPerShellMB="1024"} >> C:\winrm_log.txt
    echo 'winrs timeout: >> C:\winrm_log.txt
    echo '' >> C:\winrm_log.txt
    winrm set winrm/config @{MaxTimeoutms="1800000"} >> C:\\winrm_log.txt
    echo 'allow unencrypted: ' >> C:\winrm_log.txt
    echo '' >> C:\winrm_log.txt
    winrm set winrm/config/service @{AllowUnencrypted="true"} >> C:\\winrm_log.txt
    echo 'basic auth:' >> C:\winrm_log.txt
    echo '' >> C:\winrm_log.txt
    winrm set winrm/config/service/auth @{Basic="true"} >> C:\\winrm_log.txt
    net stop winrm
    echo 'autostart:' >> C:\winrm_log.txt
    echo '' >> C:\winrm_log.txt
    powershell Set-Service -Name winrm -StartupType Automatic >> C:\\winrm_log.txt
    net start winrm 
    echo 'enable ps remoting' >> C:\winrm_log.txt
    echo '' >> C:\winrm_log.txt
    powershell -Command "Enable-PSRemoting -SkipNetworkProfileCheck -Force" >> C:\\winrm_log.txt
    echo 'enumerate:' >> C:\winrm_log.txt
    echo '' >> C:\winrm_log.txt
    winrm enumerate winrm/config/Listener >> C:\\winrm_log.txt
