--- 
  
- name: clear logs
  ansible.windows.win_powershell:
    script: |
      Get-Content -Path "C:\Export-EventLogs\selected_channels.txt" | ForEach-Object {
      {
          Clear-EventLog -LogName "$_"
      }
      
      
