--- 

- name: Clean logs in /var/log
  become: true
  ansible.builtin.raw: |
    find /var/log -type f -regex ".*\.gz$" -delete
    find /var/log -type f -regex ".*\.[0-9]$" -delete
    
    for CLEAN in $(find /var/log/ -type f)
    do
        if [ -d $CLEAN ]
        then
          cp /dev/null  $CLEAN
        fi  
    done

    for CLEAN in $(find /var/log/samba -type f)
    do
        if [ -d $CLEAN ]
        then    
          rm -rf $CLEAN
        fi
    done

    if [ -d $CLEAN ]
    then
      rm /home/debian/tshark/
    fi      
  args:
    executable: /bin/bash    


- name: restart auditd
  become: true
  ansible.builtin.raw: |    
    if [ -f /var/log/audit/audit.log ]
    then
      sudo rm /var/log/audit/audit.log
    fi  
    sudo systemctl restart auditd
    sudo auditctl -R /home/{{ ansible_user }}/audit.rules
  args:
    executable: /bin/bash    
