--- 

- name: Clean logs in /var/log
  become: true
  ansible.builtin.raw: |
    find /var/log -type f -regex ".*\.gz$" -delete
    find /var/log -type f -regex ".*\.[0-9]$" -delete
    
    for CLEAN in $(find /var/log/ -type f)
    do
        if [ -d $CLEAN ]
        then
          cp /dev/null  $CLEAN
        fi  
    done

    for smblog in $(find /var/log/samba -type f)
    do
        rm -rf $CLEAN
    done

    if [ -d /home/debian/tshark/ ]
    then
      rm /home/debian/tshark/
    fi      

    for log in $(sudo find /var/log/audit/ -type f)
    do
      sudo rm $log
    done
  args:
    executable: /bin/bash    

 
