- hosts: aggregation_server
  gather_facts: True
  become: true
  vars:  
    hostname: aggregation-server
    ansible_user: 'debian'
  roles:
    - java_linux
    - elasticsearch_linux_5
    - kibana_linux_5
#    - filebeat_linux_5
#    - metricbeat_linux
#    - guacamole_terraform

