- hosts: aggregation-server
  gather_facts: True
  become: true
  vars:  
    hostname: aggregation-server
    ansible_user: 'debian'
  roles:
    - java_linux
    - elasticsearch_linux_7
#    - opensearch_linux_7    
    - kibana_linux_7
    - filebeat_linux_7
