- hosts: ubuntu, debian
  gather_facts: True
  become: true
  vars_files:
    - ../../configs/attack_range_default.yml
  roles:
    - set_hostname_linux
    - linux_common
    - update_sysmon_config_linux
    - linux_sysmon
    - linux_install_art
    - linux_osquery    





