- hosts: audit_linux
  gather_facts: True
  become: true
  roles:
    - linux_clear_logs
    - linux_start_auditd 
    - linux_start_wireshark


- hosts: windows
  gather_facts: true
  roles:
    - windows_clear_logs
    - windows_start_audit 
    - windows_start_wireshark


- hosts: aggregation_server
  tasks:
    #place textfile with current timestamp
    - name: place timestamp file
      become: true
      shell: |      
          date +%d-%m-%Y-%H-%M > /home/debian/dataset/timestamp.txt

