- hosts: audit_linux
  gather_facts: True
  become: true
  roles:
    - linux_stop_wireshark
    - linux_stop_auditd 
    - linux_export_logs


- hosts: windows
  gather_facts: true
  roles:
    - windows_stop_wireshark
    - windows_stop_audit 
    - windows_export_logs


- hosts: aggregation_server
  tasks:
  # insert filenames with start timestamp from textfile
  # alternate: create folder with timestamp and move files there
    - name: insert timestamps
      become: true
      shell: | 
        timestamp=$(cat /home/debian/dataset/timestamp.txt)

        for host in /home/debian/dataset/*/
        do 
          cd $host
          for file in $(find . -name "*.zip" -or -name "*.gz" | sed 's/^.\{1\}\///g')
          do
            if [ ! -d /home/debian/dataset/$host$timestamp/ ]
            then 
              mkdir $timestamp
              cd $timestamp 
              mkdir "logs"
              mkdir "network"
              cd ..  
            fi
            mv $host$file $host$timestamp/$file
            mv $host"hashes.txt" $host$timestamp/hashes.txt
          done          
          cd ..
        done
