- hosts: audit_linux
  gather_facts: True
  become: true
  vars_files:
    - ../../configs/attack_range_default.yml
  roles:
    - linux_stop_wireshark
    - linux_export_logs


- hosts: windows
  gather_facts: true
  become: true
  roles:
    - windows_stop_wireshark
    - windows_export_logs


- hosts: aggregation_server
  tasks:
  # insert filenames with start timestamp from textfile
    - name: insert timestamps
      become: true
      shell: | 
        timestamp = cat ~/dataset/timestamp.txt
        for old in ~/dataset/*.gz
        do 
          new = $(sed -e 's/_/_$timestamp_/1' <<< "$old")
          mv "$old" "$new"
        done 

        for old in ~/dataset/*.zip
        do 
          new = $(sed -e 's/_/_$timestamp_/1' <<< "$old")
          mv "$old" "$new"        
        done 
