- hosts: audit_linux
  gather_facts: True
  become: true
  roles:
    - linux_stop_wireshark
    - linux_stop_auditd 
    - linux_export_logs


- hosts: windows
  gather_facts: true
  roles:
    - windows_stop_wireshark
    - windows_stop_audit 
    - windows_export_logs


- hosts: proxy
  tasks:
  - name: stop wireshark
    become: true
    shell: |
      killall tshark

  - name: export pcap
    become: true
    shell: |
      cd "/home/{{ ansible_user }}/tshark/"
      tar -czvf "proxy_pcap.tar.gz" "proxy.pcapng"    
      scp proxy_pcap.tar.gz debian@10.0.1.12:/home/debian/dataset/proxy/network/proxy_pcap.tar.gz



- hosts: aggregation_server
  tasks:
    - name: insert timestamps
      become: true
      shell: | 
        timestamp=$(cat /home/debian/dataset/timestamp.txt)

        for host in /home/debian/dataset/*/
        do 
          cd $host
          for file in $(find . -name "*.zip" -or -name "*.gz" | sed 's/^.\{1\}\///g')
          do
            if [ ! -d /home/debian/dataset/$host$timestamp/ ]
            then 
              mkdir $timestamp
              cd $timestamp 
              mkdir "logs"
              mkdir "network"
              cd ..  
            fi
            mv $host$file $host$timestamp/$file
            mv $host"hashes.txt" $host$timestamp/hashes.txt
          done          
          cd ..
        done
