- hosts: IT-Win-Share
  gather_facts: True
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_port: 5985
    win_password: 'secreT123%'
  roles:
    - windows_fileshare