- hosts: windows
  gather_facts: True
  vars:
#    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    private_key_path: "~/.ssh/id_ed25519"
  roles:
    - windows_common
    - set_hostname_win
    - sysmon
    - update_sysmon_config 
    - red_team_tools_terraform
    - join_domain       
    - windows_install_attack_simulation
