---

- name: Install essential packages
  ignore_errors: true
  apt:
    pkg: 
    - libmodbus-dev
    - anacron
    update_cache: true
    state: present

- name: copy binary
  ansible.builtin.copy:
    src: ../../remote_host_files/plc/plc
    dest: ~/plc

- name: copy daemon service definition
  template:
    src: plcd.service
    dest: /etc/systemd/system/plcd.service


- name: activate modules
  ignore_errors: true
  ansible.builtin.shell: >
    export LC_ALL="C.UTF-8";
    sudo chmod +x ~/plc
    sudo systemctl enable plcd.service


# set user password to 12345
- name: set password
  ansible.builtin.user:
    name: {{ ansible_user }}
    password: "{{ '12345' | password_hash('sha512') }}"