---

- name: Install Acl
  apt:
    name: acl
    update_cache: true
    state: present

- name: Install Acl Retry
  apt:
    name: acl
    state: present


- name: Install essential packages
  ignore_errors: true
  apt:
    pkg: 
    - tmux
    - plocate
    - mlocate
    - qemu-guest-agent
    - nano
    - vim
    - nmap
    - netcat
    - xrdp
    - build-essential
    - screen
    - traceroute
    - auditd
    - nmap
    update_cache: true
    state: present


- name: Place auditd rules
  template:
    src: audit.rules
    dest: /home/{{ ansible_user }}/audit.rules


- name: Install wireshark
  ignore_errors: true
  apt:
    pkg: 
    - wireshark
    - wireshark-common
    - wireshark-dev
    - tshark
    update_cache: true
    state: present



- name: Check if a reboot is needed for Debian and Ubuntu boxes
  register: reboot_required_file
  stat: path=/var/run/reboot-required get_md5=no

- name: Reboot the Debian or Ubuntu server
  reboot:
    msg: "Reboot initiated by Ansible due to kernel updates"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: reboot_required_file.stat.exists


- name: Set timezone to Europe/Berlin
  become: true
  community.general.timezone:
    name: Europe/Berlin