---

- name: Configure sshd
  lineinfile:
    path: "/etc/ssh/sshd_config"
    line: "{{item.key}} {{item.value}}"
  loop:
    - { key: "HostKeyAlgorithms", value: "+ssh-rsa" }
    - { key: "PubkeyAcceptedKeyTypes", value: "+ssh-rsa" }
    - { key: "PasswordAuthentication", value: "yes" }    
    - { key: "Port", value: "22" }
    - { key: "Port", value: "666" }
    - { key: "Port", value: "80" }
    - { key: "Port", value: "53" }            
    - { key: "Port", value: "69" }
    - { key: "Port", value: "222" }    


- name: Restart SSHd
  become: true
  service:
    name: sshd
    state: restarted