---

- name: Install essential packages
  ignore_errors: true
  apt:
    pkg: 
    - libmodbus-dev
    - anacron
    update_cache: true
    state: present

- name: copy binary
  ansible.builtin.copy:
    src: hmi
    dest: /home/debian/hmi

- name: copy daemon service definition
  template:
    src: hmid.service
    dest: /etc/systemd/system/hmid.service


- name: activate modules
  ignore_errors: true
  ansible.builtin.shell: |
    export LC_ALL="C.UTF-8";
    sudo chmod +x /home/debian/hmi
    sudo systemctl enable hmid.service



# set user password to 12345
- name: set password
  ansible.builtin.user:
    name: "debian"
    password: "{{ '12345' | password_hash('sha512') }}"
