---
# - name: Add ansible repository into sources list
#   ansible.builtin.apt_repository:
#     repo: https://github.com/ansible/ansible.git
#     state: present

- name: Install Ansible
  ansible.builtin.package:
    name: ansible
    state: present

## install requirements.yaml

- name: install requirements
  ansible.builtin.shell: >
    export LC_ALL="C.UTF-8";
    ansible-galaxy install -r /home/2_ansible_resource_provisioning/requirements.yml


- name: Check if a reboot is needed for Debian and Ubuntu boxes
  register: reboot_required_file
  stat: path=/var/run/reboot-required get_md5=no

- name: Reboot the Debian or Ubuntu server
  reboot:
    msg: "Reboot initiated by Ansible due to kernel updates"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: reboot_required_file.stat.exists