---

- name: Wait for FloatIP to settle 
  ansible.builtin.pause:
    seconds: 30


- name: clone and install
  ansible.builtin.shell: |
    export LC_ALL="C.UTF-8";
    cd ~/
    mkdir poshc2
    cd poshc2 
    git clone https://github.com/nettitude/PoshC2.git
    cd PoshC2
    sudo ./Install.sh


