---


- name: stop logging 
  ansible.windows.win_shell: | 
      logman stop file_read -ets
      logman stop Powershell_payload -ets
      logman stop Registry_read -ets
      logman stop "NT Kernel Logger" -ets