---

- name: Wait for FloatIP to settle 
  ansible.builtin.pause:
    seconds: 30

- name: install nmap vuln scan scripts
  ansible.builtin.shell: |
    export LC_ALL="C.UTF-8";
    cd /usr/share/nmap/scripts/
    git clone https://github.com/vulnersCom/nmap-vulners.git


- name: Set timezone to Europe/Berlin
  become: true
  community.general.timezone:
    name: Europe/Berlin



# set user password to DragonSwordFish23%
# mkpasswd --method=sha-512 DragonSwordFish23%
- name: set password
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    password: "{{ 'kali' | password_hash('sha512')  }}" 