---

- name: Wait for FloatIP to settle 
  ansible.builtin.pause:
    seconds: 30

- name: install nmap vuln scan scripts
  ansible.builtin.shell: >
    export LC_ALL="C.UTF-8";
    cd /usr/share/nmap/scripts/
    sudo git clone https://github.com/vulnersCom/nmap-vulners.git


- name: Set timezone to Europe/Berlin
  become: true
  community.general.timezone:
    name: Europe/Berlin