---
#
# Installing Kibana
#

# Install Kibana 


## todo: specific version selector
- name: Install Kibana with apt
  apt:
   name: kibana
   update_cache: yes
 
# Configurations

# - name: Updating the config file to allow outside access
#   lineinfile:
#    destfile: /etc/kibana/kibana.yml
#    regexp: 'server.host:'
#    line: 'server.host: 0.0.0.0'

# - name: Defining server port
#   lineinfile:
#    destfile: /etc/kibana/kibana.yml
#    regexp: 'server.port:'
#    line: 'server.port: 5601'
    
# - name: Defining Elasticsearch URL
#   lineinfile:
#    destfile: /etc/kibana/kibana.yml
#    regexp: 'elasticsearch.url:'
#    line: '#elasticsearch.url: "http://localhost:9200"'
   
### todo config bauen
- name: Replace default elasticsearch.yml configurations
  template:
    src: kibana.yml
    dest: /etc/kibana/kibana.yml


# Starting Kibana

- name: Starting Kibana
  service:
   name: kibana
   state: started
