--- 


# transform to service and change status and startup type on play to enable logging beyond reboots
- name: start wireshark in background
  become: true
  ansible.builtin.raw: |
    if [ ! -d /home/"{{ ansible_user }}"/tshark/ ]
    then
      sudo mkdir "tshark/"
    fi  
    screen -d -m tshark -i any -F pcapng -w /home/"{{ ansible_user }}"/tshark/{{ hostname }}.pcapng -q &
    sleep 1