--- 

- name: start wireshark in background
  become: true
  ansible.builtin.raw: |
    hostname = $(hostname)
    if [ ! -d /home/debian/tshark/ ]
    then
      sudo mkdir "tshark/"
    fi  
    screen -d -m sudo tshark -i any -w $hostname.pcap -q &
    sleep 1