--- 

- name: start wireshark in background
  become: true
  shell: |
    hostname = $(hostname)
    if [ ! -d /home/debian/tshark/ ]
    then
      sudo mkdir "tshark/"
    fi  
    sudo tshark -i any -w $hostname.pcap -q &