--- 

- name: Get timestamp from the system
  shell: "date +%d-%m-%Y-%H-%M"
  register: timestamp

- name: Get hostname
  shell: "hostname"
  register: hostname

## maybe stop logging and resume afterwards?


- name: stop auditd
  become: true
  shell: |
    sudo systemctl stop auditd

- name: zip /var/log to one big archive
  become: true
  shell: |
    tar -czvf {{ hostname }}_{{ timestamp }}_logs.tar.gz /var/log
    tar -czvf {{ hostname }}_{{ timestamp }}_pcap.tar.gz /home/debian/tshark/$hostname.pcap


- name: Transfer logfiles file from ServerA to ServerB
  synchronize:
    src: "{{ hostname }}_{{ timestamp }}_logs.tar.gz" # /path/on/server_a # 
    dest: /home/debian/dataset/{{ hostname }}/logs/{{ hostname }}_{{ timestamp }}_logs.tar.gz  # /path/on/server_b  # 
    mode: pull
  delegate_to: aggregation_server  # server b


- name: Transfer pcap file from ServerA to ServerB
  synchronize:
    src: "{{ hostname }}_{{ timestamp }}_pcap.tar.gz"
    dest: /home/debian/dataset/{{ hostname }}/network/{{ hostname }}_{{ timestamp }}_pcap.tar.gz
    mode: pull
  delegate_to: aggregation_server  # server b