---

- name: copy sysmon config template
  become: true
  copy:
    src: "../../configs/SysMonLinux-CatchAll.xml"
    dest: "/tmp/SysMonLinux-CatchAll.xml"

- name: update sysmon config
  become: true
  ansible.builtin.shell: sysmon -c /tmp/SysMonLinux-CatchAll.xml