--- 


- name: start wireshark
  ansible.windows.win_powershell:
    script: |
      $tsharkPath = "C:\Program Files\Wireshark\tshark.exe"
      $helper1 = & $tsharkPath -D
      $helper2 = $helper1.Count - 2
      for ($i = 1; $i -le $helper2; $i++)
      {
          $interfaceArgs = -join($interfaceArgs, "-i ", $i, " ")
      }      
      $args = -join($interfaceArgs, " -w C:\Export-EventLogs\", "{{ hostname }}", ".pcapng -q")
      Invoke-Command -ComputerName localhost -ScriptBlock { Start-Process $tsharkPath -ArgumentList $args } -asJob