---

- name: Configure Guacamole Server
  shell:
    cmd: |
      echo "GUACAMOLE_HOME=/etc/guacamole" | sudo tee -a /etc/default/tomcat
      echo "export GUACAMOLE_HOME=/etc/guacamole" | sudo tee -a /etc/profile

- name: Copy guacamole.properties file
  become: true
  copy:
    src: guacamole.properties
    dest: /etc/guacamole/guacamole.properties

- name: link guacamole
  become: True
  when: link_guacamole_needed == "1"
  shell:
    cmd: |
      ln -s /etc/guacamole /opt/tomcat/tomcatapp/.guacamole

# Todo: Is this required?
# - name: Give permission
#   become: True
#   shell:
#     cmd: |
#       chown -R tomcat: /opt/tomcat

# Todo: Is the user mapping relevant?
# - name: Copy user-mapping.xml
#   when: cloud_provider != "local" #or cloud_provider == "openstack"
#   template:
#     src: user-mapping.xml
#     dest: /etc/guacamole/user-mapping.xml

- name: Create a new folder
  file:
    path: /home/ubuntu/shared-folder
    state: directory

- name: Copy user-mapping-local.xml
  template:
    src: user-mapping-local.xml
    dest: /etc/guacamole/user-mapping.xml
  when: cloud_provider == "local"

# Todo: Make restart functional
# - name: Restart guacd and tomcat
#   become: true
#   shell:
#     cmd: |
#       systemctl restart tomcat guacd