---  

# use https://github.com/WillyMoselhy/Export-EventLogs to export logs
- name: Copy log exporter
  ansible.windows.win_copy:
    src: Export-EventLogs
    dest: C:\


- name: install npcap
  ansible.windows.win_powershell:
    script: |
      Invoke-WebRequest 'https://npcap.com/dist/npcap-1.80.exe' -OutFile C:\Users\TestAdmin\Downloads\npcap-1.80-installer.exe
      Invoke-WebRequest 'https://nmap.org/dist/nmap-7.95-setup.exe' -OutFile C:\Users\TestAdmin\Downloads\nmap-setup.exe
      Start-Process "C:\Users\TestAdmin\Downloads\npcap.exe" -ArgumentList "/S /npf_startup=yes /loopback_support=yes /dlt_null=no /admin_only=no /dot11_support=no /vlan_support=no /winpcap_mode=yes"


