---
- include: set-hostname.yml
- include: windows-disable-defender.yml
#- include: windows-disable-firewall.yml
#- include: activate-ssh.yml
- include: windows-enable-ps-logging.yml
- include: windows-enable-4688-cmd-line-audit.yml
- include: install_choco.yml
  when: (cloud_provider == "local") or (cloud_provider == "openstack")
- include: install_app_chocolatey.yml
  with_items:
    - "firefox"
    - "git"
    - "notepadplusplus"
    - "7zip"
    - "adobereader"
    - "python"
    - "microsoft-office-deployment"
    - "thunderbird"
    - "wireshark"
#- include: vulners.yml
- include: applications.yml
