---


- name: Install Packages
  ignore_errors: true
  apt:
    pkg: 
    - vim
    - vi 
    - nano 
    update_cache: yes


- name: Creates directory
  ansible.builtin.file:
    path: /home/ubuntu/Documents/
    state: directory



- name: place text file1
  template:
    src: secret.txt
    dest: /home/ubuntu/Documents/secret.txt


# - name: shell stuff
#   ignore_errors: true
#   ansible.builtin.shell: >
#     export LC_ALL="C.UTF-8";


# - name: Allow 'wheel' group to have passwordless sudo
#   lineinfile:
#     dest: /etc/sudoers
#     state: present
#     regexp: '^%wheel'
#     line: 'ubuntu NOPASSWD: /usr/bin/vim'
#     validate: 'visudo -cf %s'


- name: allow sudo vim -c '!sh'
  community.general.sudoers:
    name: vim-sudo
    user: ubuntu
    commands:
      - /usr/bin/vim
    nopassword: true



# set user password to DragonSwordFish23%
# mkpasswd --method=sha-512 DragonSwordFish23%
- name: set password
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    password: "{{ 'DragonSwordFish23%' | password_hash('sha512')  }}"    #"$6$kKNjPrThe0dZSLST$ZEjlHfxA/74I20/zxjPi3WSa4nXpJ1wmh7pqpXWaR6Giv9CEM/b3LAGFXf8ApJdYSVEKg31BENSE22EFcltLh1"
